first_name = input("First Name: ")
last_name = input ("Last Name: ")
age = int(input("Age: "))
town = input("Town: ")
print(f"You are {first_name} {last_name}a, {age}-years old person from {town}. ")
print("Nice to meet you!")